### ISSUE TITLE
run_simulation sometimes fails with division by zero for some seeds

### ISSUE THREAD

**Issue by wenzeslaus** [ncsu-landscape-dynamics/popsborder#123]
The test `tests/test_cli.py` fails with:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vpetras/Projects/popsborder/popsborder/popsborder/__main__.py", line 22, in <module>
    main()
  File "/home/vpetras/Projects/popsborder/popsborder/popsborder/app.py", line 158, in main
    print_totals_as_text(args.num_consignments, config, totals)
  File "/home/vpetras/Projects/popsborder/popsborder/popsborder/outputs.py", line 505, in print_totals_as_text
    (totals.false_neg - totals.missed_within_tolerance)
ZeroDivisionError: float division by zero
```

That's an issue. Another issue is that it fails only sometimes. It should fail always if there is an error in one case. (The seed is set in the command line `'--seed', '0'`.)

**Comment by wenzeslaus** [comment]
The simulation fails using the following Python code (the first failing seed starting from 0 is 15):

```python
import yaml
from pathways.simulation import run_simulation
from pathways.outputs import print_totals_as_text

config = yaml.safe_load(open("config.yml"))
res = run_simulation(config, num_simulations=1, num_consignments=10, seed=15)
print_totals_as_text(10, config, res)
```

Or from command line:


```sh
python -m pathways --num-consignments 10 --config-file config.yml --seed 15
```

With the following config (taken from tests):

```yaml
consignment:
  boxes:
    min: 1
    max: 50
  items_per_box:
    default: 10
  origins:
  - Netherlands
  - Mexico
  flowers:
  - Hyacinthus
  - Rosa
  - Gerbera
  ports:
  - NY JFK CBP
  - FL Miami Air CBP
contamination:
  contamination_unit: items
  contamination_rate:
    distribution: beta
    parameters:
    - 4
    - 60
  arrangement: random_box
  random_box:
    probability: 0.2
    ratio: 0.5
inspection:
  unit: boxes
  within_box_proportion: 1
  sample_strategy: hypergeometric
  min_boxes: 0
  tolerance_level: 0
  proportion:
    value: 0.02
  hypergeometric:
    detection_level: 0.1
    confidence_level: 0.95
  fixed_n: 10
  selection_strategy: random
  cluster:
    cluster_selection: random
    interval: 3
```

It fails for me even a shorter config too:

```yaml
consignment:
  boxes:
    min: 1
    max: 50
  items_per_box:
    default: 10
  origins:
  - Netherlands
  flowers:
  - Hyacinthus
  - Rosa
  - Gerbera
  ports:
  - NY JFK CBP
contamination:
  contamination_unit: items
  contamination_rate:
    distribution: beta
    parameters:
    - 4
    - 60
  arrangement: random_box
  random_box:
    probability: 0.2
    ratio: 0.5
inspection:
  unit: boxes
  within_box_proportion: 1
  sample_strategy: hypergeometric
  tolerance_level: 0
  hypergeometric:
    detection_level: 0.1
    confidence_level: 0.95
  selection_strategy: random
```
